services:
  postgres:
    image: postgres:16
    container_name: transcoder-postgres2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresqldb/data

  redis:
    image: redis:7
    container_name: transcoder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    container_name: transcoder-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  # grpc:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.grpc
  #   container_name: transcoder-grpc
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     SERVER_HOST: 0.0.0.0
  #     SERVER_PORT: 8099
  #     REDIS_HOST: redis
  #     MINIO_ENDPOINT: minio:9000
  #     WEB_SERVER_URL: http://api:8084
  #     FFMPEG_PATH: /usr/bin/ffmpeg
  #     FFPROBE_PATH: /usr/bin/ffprobe
  #   depends_on:
  #     - redis
  #     - minio
  #   ports:
  #     - "8099:8099"

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   container_name: transcoder-api
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     SERVER_HOST: 0.0.0.0
  #     SERVER_PORT: 8084
  #     GRPC_SERVER_ADDR: grpc:8099
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     REDIS_HOST: redis
  #     MINIO_ENDPOINT: minio:9000
  #     FFMPEG_PATH: /usr/bin/ffmpeg
  #   depends_on:
  #     - postgres
  #     - redis
  #     - minio
  #     - grpc
  #   ports:
  #     - "8084:8084"

volumes:
  postgres-data:
  redis-data:
  minio-data:
