// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID        int32              `json:"id"`
	JobID     string             `json:"job_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PresignedUrl struct {
	ID           int32              `json:"id"`
	JobID        string             `json:"job_id"`
	PartNumber   int32              `json:"part_number"`
	PresignedUrl string             `json:"presigned_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Videometum struct {
	ID          int32              `json:"id"`
	JobID       string             `json:"job_id"`
	VideoName   pgtype.Text        `json:"video_name"`
	Description pgtype.Text        `json:"description"`
	Format      pgtype.Text        `json:"format"`
	Bitrate     pgtype.Int4        `json:"bitrate"`
	Resolution  pgtype.Text        `json:"resolution"`
	Duration    pgtype.Int4        `json:"duration"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Codec       string             `json:"codec"`
	Framerate   pgtype.Int4        `json:"framerate"`
}
