// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID        int32              `json:"id"`
	JobID     string             `json:"job_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Videometum struct {
	ID          int32              `json:"id"`
	JobID       int32              `json:"job_id"`
	VideoName   pgtype.Text        `json:"video_name"`
	Description pgtype.Text        `json:"description"`
	Format      pgtype.Text        `json:"format"`
	Bitrate     pgtype.Int4        `json:"bitrate"`
	Resolution  pgtype.Text        `json:"resolution"`
	Duration    pgtype.Int4        `json:"duration"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
