// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (job_id, status)
VALUES ($1, COALESCE($2, 'pending'))
RETURNING id, job_id, status, created_at, updated_at
`

type CreateJobParams struct {
	JobID   string      `json:"job_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.JobID, arg.Column2)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVideoMeta = `-- name: CreateVideoMeta :one
INSERT INTO videometa (
	job_id,
	video_name,
	description,
	format,
	bitrate,
	resolution,
	duration
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, video_name, description, format, bitrate, resolution, duration, created_at, updated_at
`

type CreateVideoMetaParams struct {
	JobID       int32       `json:"job_id"`
	VideoName   pgtype.Text `json:"video_name"`
	Description pgtype.Text `json:"description"`
	Format      pgtype.Text `json:"format"`
	Bitrate     pgtype.Int4 `json:"bitrate"`
	Resolution  pgtype.Text `json:"resolution"`
	Duration    pgtype.Int4 `json:"duration"`
}

func (q *Queries) CreateVideoMeta(ctx context.Context, arg CreateVideoMetaParams) (Videometum, error) {
	row := q.db.QueryRow(ctx, createVideoMeta,
		arg.JobID,
		arg.VideoName,
		arg.Description,
		arg.Format,
		arg.Bitrate,
		arg.Resolution,
		arg.Duration,
	)
	var i Videometum
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VideoName,
		&i.Description,
		&i.Format,
		&i.Bitrate,
		&i.Resolution,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const deleteVideoMeta = `-- name: DeleteVideoMeta :exec
DELETE FROM videometa
WHERE id = $1
`

func (q *Queries) DeleteVideoMeta(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVideoMeta, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, job_id, status, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByJobID = `-- name: GetJobByJobID :one
SELECT id, job_id, status, created_at, updated_at
FROM jobs
WHERE job_id = $1
`

func (q *Queries) GetJobByJobID(ctx context.Context, jobID string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByJobID, jobID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoMetaByID = `-- name: GetVideoMetaByID :one
SELECT id, job_id, video_name, description, format, bitrate, resolution, duration, created_at, updated_at
FROM videometa
WHERE id = $1
`

func (q *Queries) GetVideoMetaByID(ctx context.Context, id int32) (Videometum, error) {
	row := q.db.QueryRow(ctx, getVideoMetaByID, id)
	var i Videometum
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VideoName,
		&i.Description,
		&i.Format,
		&i.Bitrate,
		&i.Resolution,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoMetaByJobID = `-- name: GetVideoMetaByJobID :one
SELECT id, job_id, video_name, description, format, bitrate, resolution, duration, created_at, updated_at
FROM videometa
WHERE job_id = $1
`

func (q *Queries) GetVideoMetaByJobID(ctx context.Context, jobID int32) (Videometum, error) {
	row := q.db.QueryRow(ctx, getVideoMetaByJobID, jobID)
	var i Videometum
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VideoName,
		&i.Description,
		&i.Format,
		&i.Bitrate,
		&i.Resolution,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, job_id, status, created_at, updated_at
FROM jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoMeta = `-- name: ListVideoMeta :many
SELECT id, job_id, video_name, description, format, bitrate, resolution, duration, created_at, updated_at
FROM videometa
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVideoMetaParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVideoMeta(ctx context.Context, arg ListVideoMetaParams) ([]Videometum, error) {
	rows, err := q.db.Query(ctx, listVideoMeta, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Videometum
	for rows.Next() {
		var i Videometum
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.VideoName,
			&i.Description,
			&i.Format,
			&i.Bitrate,
			&i.Resolution,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_id, status, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoMeta = `-- name: UpdateVideoMeta :one
UPDATE videometa
SET video_name = $2,
	description = $3,
	format = $4,
	bitrate = $5,
	resolution = $6,
	duration = $7,
	updated_at = NOW()
WHERE id = $1
RETURNING id, job_id, video_name, description, format, bitrate, resolution, duration, created_at, updated_at
`

type UpdateVideoMetaParams struct {
	ID          int32       `json:"id"`
	VideoName   pgtype.Text `json:"video_name"`
	Description pgtype.Text `json:"description"`
	Format      pgtype.Text `json:"format"`
	Bitrate     pgtype.Int4 `json:"bitrate"`
	Resolution  pgtype.Text `json:"resolution"`
	Duration    pgtype.Int4 `json:"duration"`
}

func (q *Queries) UpdateVideoMeta(ctx context.Context, arg UpdateVideoMetaParams) (Videometum, error) {
	row := q.db.QueryRow(ctx, updateVideoMeta,
		arg.ID,
		arg.VideoName,
		arg.Description,
		arg.Format,
		arg.Bitrate,
		arg.Resolution,
		arg.Duration,
	)
	var i Videometum
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VideoName,
		&i.Description,
		&i.Format,
		&i.Bitrate,
		&i.Resolution,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
