// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateVideoMeta(ctx context.Context, arg CreateVideoMetaParams) (Videometum, error)
	DeleteJob(ctx context.Context, id int32) error
	DeleteVideoMeta(ctx context.Context, id int32) error
	GetJobByID(ctx context.Context, id int32) (Job, error)
	GetJobByJobID(ctx context.Context, jobID string) (Job, error)
	GetVideoMetaByID(ctx context.Context, id int32) (Videometum, error)
	GetVideoMetaByJobID(ctx context.Context, jobID int32) (Videometum, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListVideoMeta(ctx context.Context, arg ListVideoMetaParams) ([]Videometum, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	UpdateVideoMeta(ctx context.Context, arg UpdateVideoMetaParams) (Videometum, error)
}

var _ Querier = (*Queries)(nil)
