// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jobs/{id}/source-url": {
            "get": {
                "description": "Retrieve a presigned GET URL for a job's uploaded source video",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get source video URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Source URL retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            }
        },
        "/status/{id}/update": {
            "get": {
                "description": "Retrieve the current status for a job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Job status retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "Transition a job from one status to another",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Update job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status transition payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status updated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            }
        },
        "/upload/complete": {
            "post": {
                "description": "Finish uploading video parts and create metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Complete a multipart upload",
                "parameters": [
                    {
                        "description": "Upload completion request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MultipartCompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload completed successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            }
        },
        "/upload/initiate": {
            "post": {
                "description": "Start a new multipart upload for a video file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Initiate a multipart upload",
                "parameters": [
                    {
                        "description": "Upload initiation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MultipartInitiateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload initiated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ApiMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.MultipartCompleteRequest": {
            "type": "object",
            "required": [
                "format",
                "job_id",
                "parts",
                "upload_id"
            ],
            "properties": {
                "codec": {
                    "description": "h.264 or h.265",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "format": {
                    "description": "mp4 or mov",
                    "type": "string"
                },
                "framerate": {
                    "description": "1920x1080",
                    "type": "integer"
                },
                "job_id": {
                    "type": "string"
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MultipartUploadPart"
                    }
                },
                "upload_id": {
                    "type": "string"
                },
                "video_name": {
                    "type": "string"
                }
            }
        },
        "models.MultipartInitiateRequest": {
            "type": "object",
            "required": [
                "file_size"
            ],
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "part_size": {
                    "type": "integer"
                }
            }
        },
        "models.MultipartUploadPart": {
            "type": "object",
            "required": [
                "etag",
                "part_number"
            ],
            "properties": {
                "etag": {
                    "type": "string"
                },
                "part_number": {
                    "type": "integer"
                }
            }
        },
        "models.Status": {
            "type": "string",
            "enum": [
                "pending",
                "queued",
                "downloading",
                "processing",
                "uploading",
                "completed",
                "failed",
                "cancelled"
            ],
            "x-enum-comments": {
                "StatusUploading": "after transcoding has been done, we upload back to minio"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "after transcoding has been done, we upload back to minio",
                "",
                "",
                ""
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusQueued",
                "StatusDownloading",
                "StatusProcessing",
                "StatusUploading",
                "StatusCompleted",
                "StatusFailed",
                "StatusCancelled"
            ]
        },
        "models.UpdateStatusRequest": {
            "type": "object",
            "required": [
                "from",
                "id",
                "to"
            ],
            "properties": {
                "from": {
                    "enum": [
                        "pending",
                        "queued",
                        "downloading",
                        "processing",
                        "uploading",
                        "completed",
                        "failed",
                        "cancelled"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Status"
                        }
                    ]
                },
                "id": {
                    "type": "string"
                },
                "to": {
                    "enum": [
                        "pending",
                        "queued",
                        "downloading",
                        "processing",
                        "uploading",
                        "completed",
                        "failed",
                        "cancelled"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Status"
                        }
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8084",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Transcoder API",
	Description:      "API for transcoding workflows with multipart upload support.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
