// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/upload/complete": {
            "post": {
                "description": "Finish uploading video parts and create metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Complete a multipart upload",
                "parameters": [
                    {
                        "description": "Upload completion request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MultipartCompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload completed successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            }
        },
        "/upload/initiate": {
            "post": {
                "description": "Start a new multipart upload for a video file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Initiate a multipart upload",
                "parameters": [
                    {
                        "description": "Upload initiation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MultipartInitiateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload initiated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ApiMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ApiMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.MultipartCompleteRequest": {
            "type": "object",
            "required": [
                "job_id",
                "parts",
                "upload_id"
            ],
            "properties": {
                "bitrate": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "format": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MultipartUploadPart"
                    }
                },
                "resolution": {
                    "type": "string"
                },
                "upload_id": {
                    "type": "string"
                },
                "video_name": {
                    "type": "string"
                }
            }
        },
        "models.MultipartInitiateRequest": {
            "type": "object",
            "required": [
                "file_size"
            ],
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "part_size": {
                    "type": "integer"
                }
            }
        },
        "models.MultipartUploadPart": {
            "type": "object",
            "required": [
                "etag",
                "part_number"
            ],
            "properties": {
                "etag": {
                    "type": "string"
                },
                "part_number": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8084",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Transcoder API",
	Description:      "API for transcoding workflows with multipart upload support.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
